language: node_js
node_js:
  - "9"
before_install:
  - npm i -g npm@6.8.0
cache: npm
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'