export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const SAVE_RECIPE = "SAVE_RECIPE";