language: node_js
node_js:
  - "node"
  - "9"
before_install:
  - npm i -g npm@6.8.0
install:
  - cd src/client
  - npm install 
  - cd ../server
  - npm install 
cache:
  directories:
    - "./node_modules"
    - "./client/node_modules"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - cd src/server
script:
  - npm run test
notifications:
  slack: nyu-agile-software:4tlDnPkWGzoTHwp9oNewy0wo
